export const TOGGLE_THEME = 'TOGGLE_THEME';
export const TOGGLE_SIMPLIFIED_MODE = 'TOGGLE_SIMPLIFIED_MODE';

export const ADD_TO_HISTORY = 'ADD_TO_HISTORY';
export const CLEAR_HISTORY = 'CLEAR_HISTORY';
